# Generated by Django 2.0 on 2019-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=16)),
                ('count', models.IntegerField(default=5)),
            ],
        ),
    ]
