# Generated by Django 2.0 on 2019-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_borrow',
            name='book_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
