# Generated by Django 2.0 on 2019-05-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('book_autor', models.CharField(max_length=20)),
                ('book_stock', models.IntegerField()),
                ('book_ISBN', models.CharField(max_length=20)),
            ],
        ),
    ]
